### ISSUE TITLE
Readme.md or Readme.rst ?

### ISSUE THREAD

**Issue by jmg22** [makerplane/pyAvMap#6]
In setup.py at line 5, reference to README.rst but the real file is README.md

**Comment by s-celles** [comment]
Pypi now supports Markdown

See https://stackoverflow.com/questions/26737222/how-to-make-pypi-description-markdown-work
https://packaging.python.org/guides/making-a-pypi-friendly-readme/

But reStructuredText is still widely used in Python development

But you are right... it's currently inconsistent.
